# Generated by Django 5.2.6 on 2025-09-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('date_in', models.DateTimeField(verbose_name='Дата отлета')),
                ('date_out', models.DateTimeField(verbose_name='Дата прилета')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
