# Generated by Django 5.2.6 on 2025-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_in',
            field=models.CharField(verbose_name='Дата отлета'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_out',
            field=models.CharField(verbose_name='Дата прилета'),
        ),
    ]
