# Generated by Django 5.2.6 on 2025-09-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_trip_date_in_alter_trip_date_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
